services:
  - type: web
    name: transport-ai-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: "5000"
      - key: CORS_ORIGIN
        value: "https://transport-ai-frontend.onrender.com"

  - type: static
    name: transport-ai-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: "https://transport-ai-backend.onrender.com/api"