services:
  - type: web
    name: transport-ai-backend
    env: node
    root: .
    buildCommand: |
      cd backend
      npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: "10000"
      - key: CORS_ORIGIN
        value: "https://transport-ai-frontend.onrender.com"

  - type: static
    name: transport-ai-frontend
    env: static
    root: .
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: "https://transport-ai-backend.onrender.com/api"